repo_name: "agile611/curso-devops-introduccion-a-integracion-continua-y-jenkins"
site_name: "Curso DevOps: Introducción a Integración Continua y Jenkins"
site_description: "Curso DevOps: Introducción a Integración Continua y Jenkins"
site_author: "Guillem Hernandez Sola"
site_url: "https://agile611.github.io/curso-devops-introduccion-a-integracion-continua-y-jenkins/"

repo_url: "https://github.com/agile611/curso-devops-introduccion-a-integracion-continua-y-jenkins"
docs_dir: "docs"
site_dir: "site"

theme:
  name: "material"
  language: "es"
  
  logo: "https://www.agile611.com/wp-content/uploads/2020/09/Negativo.png"
  favicon: "https://www.agile611.com/wp-content/uploads/2019/07/cropped-agile611-1-e1563910774746-1-32x32.png"

  font:
    text: "Nunito"
    code: "Nunito"

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.suggest

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: "Cambiar a modo oscuro"

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: "Cambiar a modo claro"

  icon:
    logo: material/chart-timeline-variant
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search:
      lang:
        - es

extra_css:
  - assets/css/custom.css

extra_javascript:
  - assets/js/custom.js

nav:
  - Inicio: index.md
  - El curso:
      - Introducción: 00-el-curso/00-00-index.md
      - Objetivos del curso: 00-el-curso/00-01-objetivos.md
      - Requisitos previos: 00-el-curso/00-02-requisitos-previos.md
      - Instalación de Jenkins: 00-el-curso/00-03-instalacion-jenkins.md
  - Fundamentos:
      - ¿Quién es DevOps?: 01-fundamentos/01_quien_es_devops.md
      - CI vs. CD vs. CD: 01-fundamentos/02_ci_vs_cd_vs_cd.md
      - Entorno de trabajo: 01-fundamentos/03_entorno_de_trabajo.md
      - Repositorio de código: 01-fundamentos/04_repositorio_de_codigo.md
      - Arquitectura y instalación: 01-fundamentos/05_architectura_y_instalacion.md
      - Conclusiones DevOps y CI/CD: 01-fundamentos/06_conclusiones_devops_y_ci_cd.md
      - ¿Qué es un job de Jenkins?: 01-fundamentos/07_que_es_un_job_de_jenkins.md
      - El primer job (Freestyle): 01-fundamentos/08_el_primer_job_freestyle.md
      - ¿Qué es un Agente (Node) en Jenkins?: 01-fundamentos/09_que_es_un_agente_node.md
      - Conectando un Agente: 01-fundamentos/10_conectando_un_agente.md
      - ¿Qué es un Pipeline de Jenkins?: 01-fundamentos/11_que_es_un_pipeline.md
      - El primer pipeline: 01-fundamentos/12_el_primer_pipeline.md
  - Pipelines:
      - Anatomía de un Jenkinsfile: 02-pipelines/01_anatomia_de_un_jenkinsfile.md
      - Pipeline Distribuido: 02-pipelines/02_pipeline_distribuido.md
      - ¿Por qué hacer servir el SCM para los Jenkinsfile?: 02-pipelines/03_scm_y_jenkinsfile.md
      - De local a Jenkins: 02-pipelines/04_de_local_a_jenkins.md
      - Parámetros y variables de entorno: 02-pipelines/05_parametros_y_variables.md
      - Pipeline Interactivo: 02-pipelines/06_pipeline_interactivo.md
      - Options, Post & Notifications: 02-pipelines/07_options_post_notifications.md
      - Control de errores (Timeout): 02-pipelines/08_control_de_errores.md
      - El bloque script: 02-pipelines/09_el_bloque_script.md
      - Capturando datos: 02-pipelines/10_capturando_datos.md
      - Construcción completa de una aplicación: 02-pipelines/11_construccion_completa.md
  - Miscelánea:
      - Configuración de agentes efímeros (Docker Cloud): 03-miscelania/01_configuracion_agentes_efimeros.md
  - Terraform:
      - ¿Por qué Terraform?: 04-terraform/01_por_que_terraform.md
      - Preparación del entorno: 04-terraform/02_preparacion_del_entorno.md
      - Gestión de credenciales: 04-terraform/03_gestion_de_credenciales.md
      - Un secreto simulado: 04-terraform/04_pipeline_stage_init_plan.md
      - Creando el plan: 04-terraform/05_creando_el_plan.md
      - Aprobación manual: 04-terraform/06_pipeline_stage_apply_human_approval.md
      - Modificando la Infraestructura: 04-terraform/07_modificando_la_infraestructura.md
  - Ansible:
      - ¿Por qué Ansible?: 05-ansible/01_por_que_ansible.md
      - El tu primer playbook: 05-ansible/02_el_primer_playbook.md
      - Orquestación completa: 05-ansible/03_orquestacion_completa.md
  - Referencias:
      - Documentación oficial: 06-referencias/01_documentacion_oficial.md
      - Recursos útiles: 06-referencias/02_recursos_utiles.md
      - Glosario de términos: 06-referencias/03_glosario_de_terminos.md

copyright: "© Agile611 · Licencia CC BY-NC 4.0 · Guillem Hernández Sola"