repo_name: agile611/curso-devops-introduccion-a-integracion-continua-y-jenkins
site_name: "Curso DevOps: Introducción a Integración Continua y Jenkins"
site_description: "Curso DevOps: Introducción a Integración Continua y Jenkins"
site_author: "Guillem Hernandez Sola"
site_url: "https://agile611.github.io/curso-devops-introduccion-a-integracion-continua-y-jenkins/"

repo_name: "agile611/startusinggrafana"
repo_url: "https://github.com/agile611/curso-devops-introduccion-a-integracion-continua-y-jenkins"
docs_dir: "docs"
site_dir: "site"

theme:
  name: "material"
  language: "es"

  logo: "https://www.agile611.com/wp-content/uploads/2020/09/Negativo.png"
  favicon: "https://www.agile611.com/wp-content/uploads/2019/07/cropped-agile611-1-e1563910774746-1-32x32.png"

  font:
    text: "Nunito"
    code: "Nunito"

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.suggest

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: "Cambiar a modo oscuro"

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: "Cambiar a modo claro"

  icon:
    logo: material/chart-timeline-variant
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search:
      lang:
        - es

extra_css:
  - assets/css/custom.css

extra_javascript:
  - assets/js/custom.js

nav:
  - Inicio: index.md
  - El curso:
      - Introducción: 00-el-curso/00-00-index.md
      - Objetivos del curso: 00-el-curso/00-01-objetivos.md
      - Requisitos previos: 00-el-curso/00-02-requisitos-previos.md
  - Integración Continua y Jenkins:
      - Introducción a DevOps y la integración continua: 01-introduccion_devops.md
      - Arquitectura Jenkins: 02_architectura_jenkins.md
      - Pipelines: 03_pipelines.md
      - Node: 04_node.md
      - Agent: 05_agent.md
      - Parameters: 06_parameters.md
      - Environment: 07_environment.md
      - Options: 08_options.md
      - Stages: 09_stages.md
      - Stage: 10_stage.md
      - Step: 11_step.md
      - Script: 12_script.md
      - Jobs: 13_jobs.md
      - Instalando Git y GitHub Plugin: 14_instalando_git_y_github_plugin.md
      - Creando nuestros primeros pipelines: 15_creando_nuestros_primeros_pipelines.md
      - Integración con Terraform: 16_integracion_con_terraform.md
      - Integración con Ansible: 17_integracion_con_ansible.md

copyright: "© Agile611 · Licencia CC BY-NC 4.0 · Guillem Hernández Sola"